package com.path.gateway.dbmaps.vo;

import java.math.BigDecimal;

public class GTW_CHANNEL_JMSVO extends GTW_CHANNEL_JMSVOKey {
    /**
     * This field corresponds to the database column GTW_CHANNEL_JMS.CHANNEL_ID
     */
    private BigDecimal CHANNEL_ID;

    /**
     * This field corresponds to the database column GTW_CHANNEL_JMS.QUEUE_NAME
     */
    private String QUEUE_NAME;

    /**
     * This field corresponds to the database column GTW_CHANNEL_JMS.JMS_USER
     */
    private String JMS_USER;

    /**
     * This field corresponds to the database column GTW_CHANNEL_JMS.JMS_PASSWORD
     */
    private String JMS_PASSWORD;

    /**
     * This field corresponds to the database column GTW_CHANNEL_JMS.CONSUMER_NUMBER
     */
    private BigDecimal CONSUMER_NUMBER;

    /**
     * This field corresponds to the database column GTW_CHANNEL_JMS.PRODUCER_NUMBER
     */
    private BigDecimal PRODUCER_NUMBER;

    /**
     * This field corresponds to the database column GTW_CHANNEL_JMS.PROVIDER
     */
    private String PROVIDER;
    
    /**
     * This field corresponds to the database column GTW_CHANNEL_JMS.RETRY
     */
    private BigDecimal RETRY;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_CHANNEL_JMS.CHANNEL_ID
     *
     * @return the value of GTW_CHANNEL_JMS.CHANNEL_ID
     */
    public BigDecimal getCHANNEL_ID() {
        return CHANNEL_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_CHANNEL_JMS.CHANNEL_ID
     *
     * @param CHANNEL_ID the value for GTW_CHANNEL_JMS.CHANNEL_ID
     */
    public void setCHANNEL_ID(BigDecimal CHANNEL_ID) {
        this.CHANNEL_ID = CHANNEL_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_CHANNEL_JMS.QUEUE_NAME
     *
     * @return the value of GTW_CHANNEL_JMS.QUEUE_NAME
     */
    public String getQUEUE_NAME() {
        return QUEUE_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_CHANNEL_JMS.QUEUE_NAME
     *
     * @param QUEUE_NAME the value for GTW_CHANNEL_JMS.QUEUE_NAME
     */
    public void setQUEUE_NAME(String QUEUE_NAME) {
        this.QUEUE_NAME = QUEUE_NAME == null ? null : QUEUE_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_CHANNEL_JMS.JMS_USER
     *
     * @return the value of GTW_CHANNEL_JMS.JMS_USER
     */
    public String getJMS_USER() {
        return JMS_USER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_CHANNEL_JMS.JMS_USER
     *
     * @param JMS_USER the value for GTW_CHANNEL_JMS.JMS_USER
     */
    public void setJMS_USER(String JMS_USER) {
        this.JMS_USER = JMS_USER == null ? null : JMS_USER.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_CHANNEL_JMS.JMS_PASSWORD
     *
     * @return the value of GTW_CHANNEL_JMS.JMS_PASSWORD
     */
    public String getJMS_PASSWORD() {
        return JMS_PASSWORD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_CHANNEL_JMS.JMS_PASSWORD
     *
     * @param JMS_PASSWORD the value for GTW_CHANNEL_JMS.JMS_PASSWORD
     */
    public void setJMS_PASSWORD(String JMS_PASSWORD) {
        this.JMS_PASSWORD = JMS_PASSWORD == null ? null : JMS_PASSWORD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_CHANNEL_JMS.CONSUMER_NUMBER
     *
     * @return the value of GTW_CHANNEL_JMS.CONSUMER_NUMBER
     */
    public BigDecimal getCONSUMER_NUMBER() {
        return CONSUMER_NUMBER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_CHANNEL_JMS.CONSUMER_NUMBER
     *
     * @param CONSUMER_NUMBER the value for GTW_CHANNEL_JMS.CONSUMER_NUMBER
     */
    public void setCONSUMER_NUMBER(BigDecimal CONSUMER_NUMBER) {
        this.CONSUMER_NUMBER = CONSUMER_NUMBER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_CHANNEL_JMS.PRODUCER_NUMBER
     *
     * @return the value of GTW_CHANNEL_JMS.PRODUCER_NUMBER
     */
    public BigDecimal getPRODUCER_NUMBER() {
        return PRODUCER_NUMBER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_CHANNEL_JMS.PRODUCER_NUMBER
     *
     * @param PRODUCER_NUMBER the value for GTW_CHANNEL_JMS.PRODUCER_NUMBER
     */
    public void setPRODUCER_NUMBER(BigDecimal PRODUCER_NUMBER) {
        this.PRODUCER_NUMBER = PRODUCER_NUMBER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_CHANNEL_JMS.PROVIDER
     *
     * @return the value of GTW_CHANNEL_JMS.PROVIDER
     */
    public String getPROVIDER() {
        return PROVIDER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_CHANNEL_JMS.PROVIDER
     *
     * @param PROVIDER the value for GTW_CHANNEL_JMS.PROVIDER
     */
    public void setPROVIDER(String PROVIDER) {
        this.PROVIDER = PROVIDER == null ? null : PROVIDER.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_CHANNEL_JMS.RETRY
     *
     * @return the value of GTW_CHANNEL_JMS.RETRY
     */
    public BigDecimal getRETRY() {
        return RETRY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_CHANNEL_JMS.RETRY
     *
     * @param RETRY the value for GTW_CHANNEL_JMS.RETRY
     */
    public void setRETRY(BigDecimal RETRY) {
        this.RETRY = RETRY;
    }
}