package com.path.gateway.dbmaps.vo;

import java.math.BigDecimal;

import com.path.lib.vo.BaseVO;

public class GTW_CHANNEL_ISO_INT_PARAMSVO extends BaseVO {
    /**
     * This field corresponds to the database column GTW_CHANNEL_ISO_INT_PARAMS.GTW_CHANNEL_PARAMS_ID
     */
    private BigDecimal GTW_CHANNEL_PARAMS_ID;

    /**
     * This field corresponds to the database column GTW_CHANNEL_ISO_INT_PARAMS.CHANNEL_ID
     */
    private BigDecimal CHANNEL_ID;

    /**
     * This field corresponds to the database column GTW_CHANNEL_ISO_INT_PARAMS.ENGN_ACCEPTOR_WORKER_NO
     */
    private BigDecimal ENGN_ACCEPTOR_WORKER_NO;

    /**
     * This field corresponds to the database column GTW_CHANNEL_ISO_INT_PARAMS.ENGN_WORKER_NO
     */
    private BigDecimal ENGN_WORKER_NO;

    /**
     * This field corresponds to the database column GTW_CHANNEL_ISO_INT_PARAMS.ENGN_ADD_LOGGING_HANDLER_YN
     */
    private String ENGN_ADD_LOGGING_HANDLER_YN;

    /**
     * This field corresponds to the database column GTW_CHANNEL_ISO_INT_PARAMS.ENGN_ADD_ECHO_MSG_LISTENER_YN
     */
    private String ENGN_ADD_ECHO_MSG_LISTENER_YN;

    /**
     * This field corresponds to the database column GTW_CHANNEL_ISO_INT_PARAMS.ENGN_LOG_FIELD_DESCRIPTION_YN
     */
    private String ENGN_LOG_FIELD_DESCRIPTION_YN;

    /**
     * This field corresponds to the database column GTW_CHANNEL_ISO_INT_PARAMS.ENGN_LOG_SENSITIVE_DATA_YN
     */
    private String ENGN_LOG_SENSITIVE_DATA_YN;

    /**
     * This field corresponds to the database column GTW_CHANNEL_ISO_INT_PARAMS.ENGN_REPLY_ON_ERROR_YN
     */
    private String ENGN_REPLY_ON_ERROR_YN;

    /**
     * This field corresponds to the database column GTW_CHANNEL_ISO_INT_PARAMS.ENGN_IDLE_TIMEOUT
     */
    private BigDecimal ENGN_IDLE_TIMEOUT;

    /**
     * This field corresponds to the database column GTW_CHANNEL_ISO_INT_PARAMS.ENGN_CHARSET
     */
    private String ENGN_CHARSET;

    /**
     * This field corresponds to the database column GTW_CHANNEL_ISO_INT_PARAMS.TASK_CONTAINER_CONSUMER_NO
     */
    private BigDecimal TASK_CONTAINER_CONSUMER_NO;

    /**
     * This field corresponds to the database column GTW_CHANNEL_ISO_INT_PARAMS.TASK_CONTAINER_SESSION_NO
     */
    private BigDecimal TASK_CONTAINER_SESSION_NO;

    /**
     * This field corresponds to the database column GTW_CHANNEL_ISO_INT_PARAMS.TASK_CONTAINER_DESTINATION
     */
    private String TASK_CONTAINER_DESTINATION;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_CHANNEL_ISO_INT_PARAMS.GTW_CHANNEL_PARAMS_ID
     *
     * @return the value of GTW_CHANNEL_ISO_INT_PARAMS.GTW_CHANNEL_PARAMS_ID
     */
    public BigDecimal getGTW_CHANNEL_PARAMS_ID() {
        return GTW_CHANNEL_PARAMS_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_CHANNEL_ISO_INT_PARAMS.GTW_CHANNEL_PARAMS_ID
     *
     * @param GTW_CHANNEL_PARAMS_ID the value for GTW_CHANNEL_ISO_INT_PARAMS.GTW_CHANNEL_PARAMS_ID
     */
    public void setGTW_CHANNEL_PARAMS_ID(BigDecimal GTW_CHANNEL_PARAMS_ID) {
        this.GTW_CHANNEL_PARAMS_ID = GTW_CHANNEL_PARAMS_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_CHANNEL_ISO_INT_PARAMS.CHANNEL_ID
     *
     * @return the value of GTW_CHANNEL_ISO_INT_PARAMS.CHANNEL_ID
     */
    public BigDecimal getCHANNEL_ID() {
        return CHANNEL_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_CHANNEL_ISO_INT_PARAMS.CHANNEL_ID
     *
     * @param CHANNEL_ID the value for GTW_CHANNEL_ISO_INT_PARAMS.CHANNEL_ID
     */
    public void setCHANNEL_ID(BigDecimal CHANNEL_ID) {
        this.CHANNEL_ID = CHANNEL_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_CHANNEL_ISO_INT_PARAMS.ENGN_ACCEPTOR_WORKER_NO
     *
     * @return the value of GTW_CHANNEL_ISO_INT_PARAMS.ENGN_ACCEPTOR_WORKER_NO
     */
    public BigDecimal getENGN_ACCEPTOR_WORKER_NO() {
        return ENGN_ACCEPTOR_WORKER_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_CHANNEL_ISO_INT_PARAMS.ENGN_ACCEPTOR_WORKER_NO
     *
     * @param ENGN_ACCEPTOR_WORKER_NO the value for GTW_CHANNEL_ISO_INT_PARAMS.ENGN_ACCEPTOR_WORKER_NO
     */
    public void setENGN_ACCEPTOR_WORKER_NO(BigDecimal ENGN_ACCEPTOR_WORKER_NO) {
        this.ENGN_ACCEPTOR_WORKER_NO = ENGN_ACCEPTOR_WORKER_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_CHANNEL_ISO_INT_PARAMS.ENGN_WORKER_NO
     *
     * @return the value of GTW_CHANNEL_ISO_INT_PARAMS.ENGN_WORKER_NO
     */
    public BigDecimal getENGN_WORKER_NO() {
        return ENGN_WORKER_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_CHANNEL_ISO_INT_PARAMS.ENGN_WORKER_NO
     *
     * @param ENGN_WORKER_NO the value for GTW_CHANNEL_ISO_INT_PARAMS.ENGN_WORKER_NO
     */
    public void setENGN_WORKER_NO(BigDecimal ENGN_WORKER_NO) {
        this.ENGN_WORKER_NO = ENGN_WORKER_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_CHANNEL_ISO_INT_PARAMS.ENGN_ADD_LOGGING_HANDLER_YN
     *
     * @return the value of GTW_CHANNEL_ISO_INT_PARAMS.ENGN_ADD_LOGGING_HANDLER_YN
     */
    public String getENGN_ADD_LOGGING_HANDLER_YN() {
        return ENGN_ADD_LOGGING_HANDLER_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_CHANNEL_ISO_INT_PARAMS.ENGN_ADD_LOGGING_HANDLER_YN
     *
     * @param ENGN_ADD_LOGGING_HANDLER_YN the value for GTW_CHANNEL_ISO_INT_PARAMS.ENGN_ADD_LOGGING_HANDLER_YN
     */
    public void setENGN_ADD_LOGGING_HANDLER_YN(String ENGN_ADD_LOGGING_HANDLER_YN) {
        this.ENGN_ADD_LOGGING_HANDLER_YN = ENGN_ADD_LOGGING_HANDLER_YN == null ? null : ENGN_ADD_LOGGING_HANDLER_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_CHANNEL_ISO_INT_PARAMS.ENGN_ADD_ECHO_MSG_LISTENER_YN
     *
     * @return the value of GTW_CHANNEL_ISO_INT_PARAMS.ENGN_ADD_ECHO_MSG_LISTENER_YN
     */
    public String getENGN_ADD_ECHO_MSG_LISTENER_YN() {
        return ENGN_ADD_ECHO_MSG_LISTENER_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_CHANNEL_ISO_INT_PARAMS.ENGN_ADD_ECHO_MSG_LISTENER_YN
     *
     * @param ENGN_ADD_ECHO_MSG_LISTENER_YN the value for GTW_CHANNEL_ISO_INT_PARAMS.ENGN_ADD_ECHO_MSG_LISTENER_YN
     */
    public void setENGN_ADD_ECHO_MSG_LISTENER_YN(String ENGN_ADD_ECHO_MSG_LISTENER_YN) {
        this.ENGN_ADD_ECHO_MSG_LISTENER_YN = ENGN_ADD_ECHO_MSG_LISTENER_YN == null ? null : ENGN_ADD_ECHO_MSG_LISTENER_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_CHANNEL_ISO_INT_PARAMS.ENGN_LOG_FIELD_DESCRIPTION_YN
     *
     * @return the value of GTW_CHANNEL_ISO_INT_PARAMS.ENGN_LOG_FIELD_DESCRIPTION_YN
     */
    public String getENGN_LOG_FIELD_DESCRIPTION_YN() {
        return ENGN_LOG_FIELD_DESCRIPTION_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_CHANNEL_ISO_INT_PARAMS.ENGN_LOG_FIELD_DESCRIPTION_YN
     *
     * @param ENGN_LOG_FIELD_DESCRIPTION_YN the value for GTW_CHANNEL_ISO_INT_PARAMS.ENGN_LOG_FIELD_DESCRIPTION_YN
     */
    public void setENGN_LOG_FIELD_DESCRIPTION_YN(String ENGN_LOG_FIELD_DESCRIPTION_YN) {
        this.ENGN_LOG_FIELD_DESCRIPTION_YN = ENGN_LOG_FIELD_DESCRIPTION_YN == null ? null : ENGN_LOG_FIELD_DESCRIPTION_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_CHANNEL_ISO_INT_PARAMS.ENGN_LOG_SENSITIVE_DATA_YN
     *
     * @return the value of GTW_CHANNEL_ISO_INT_PARAMS.ENGN_LOG_SENSITIVE_DATA_YN
     */
    public String getENGN_LOG_SENSITIVE_DATA_YN() {
        return ENGN_LOG_SENSITIVE_DATA_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_CHANNEL_ISO_INT_PARAMS.ENGN_LOG_SENSITIVE_DATA_YN
     *
     * @param ENGN_LOG_SENSITIVE_DATA_YN the value for GTW_CHANNEL_ISO_INT_PARAMS.ENGN_LOG_SENSITIVE_DATA_YN
     */
    public void setENGN_LOG_SENSITIVE_DATA_YN(String ENGN_LOG_SENSITIVE_DATA_YN) {
        this.ENGN_LOG_SENSITIVE_DATA_YN = ENGN_LOG_SENSITIVE_DATA_YN == null ? null : ENGN_LOG_SENSITIVE_DATA_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_CHANNEL_ISO_INT_PARAMS.ENGN_REPLY_ON_ERROR_YN
     *
     * @return the value of GTW_CHANNEL_ISO_INT_PARAMS.ENGN_REPLY_ON_ERROR_YN
     */
    public String getENGN_REPLY_ON_ERROR_YN() {
        return ENGN_REPLY_ON_ERROR_YN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_CHANNEL_ISO_INT_PARAMS.ENGN_REPLY_ON_ERROR_YN
     *
     * @param ENGN_REPLY_ON_ERROR_YN the value for GTW_CHANNEL_ISO_INT_PARAMS.ENGN_REPLY_ON_ERROR_YN
     */
    public void setENGN_REPLY_ON_ERROR_YN(String ENGN_REPLY_ON_ERROR_YN) {
        this.ENGN_REPLY_ON_ERROR_YN = ENGN_REPLY_ON_ERROR_YN == null ? null : ENGN_REPLY_ON_ERROR_YN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_CHANNEL_ISO_INT_PARAMS.ENGN_IDLE_TIMEOUT
     *
     * @return the value of GTW_CHANNEL_ISO_INT_PARAMS.ENGN_IDLE_TIMEOUT
     */
    public BigDecimal getENGN_IDLE_TIMEOUT() {
        return ENGN_IDLE_TIMEOUT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_CHANNEL_ISO_INT_PARAMS.ENGN_IDLE_TIMEOUT
     *
     * @param ENGN_IDLE_TIMEOUT the value for GTW_CHANNEL_ISO_INT_PARAMS.ENGN_IDLE_TIMEOUT
     */
    public void setENGN_IDLE_TIMEOUT(BigDecimal ENGN_IDLE_TIMEOUT) {
        this.ENGN_IDLE_TIMEOUT = ENGN_IDLE_TIMEOUT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_CHANNEL_ISO_INT_PARAMS.ENGN_CHARSET
     *
     * @return the value of GTW_CHANNEL_ISO_INT_PARAMS.ENGN_CHARSET
     */
    public String getENGN_CHARSET() {
        return ENGN_CHARSET;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_CHANNEL_ISO_INT_PARAMS.ENGN_CHARSET
     *
     * @param ENGN_CHARSET the value for GTW_CHANNEL_ISO_INT_PARAMS.ENGN_CHARSET
     */
    public void setENGN_CHARSET(String ENGN_CHARSET) {
        this.ENGN_CHARSET = ENGN_CHARSET == null ? null : ENGN_CHARSET.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_CHANNEL_ISO_INT_PARAMS.TASK_CONTAINER_CONSUMER_NO
     *
     * @return the value of GTW_CHANNEL_ISO_INT_PARAMS.TASK_CONTAINER_CONSUMER_NO
     */
    public BigDecimal getTASK_CONTAINER_CONSUMER_NO() {
        return TASK_CONTAINER_CONSUMER_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_CHANNEL_ISO_INT_PARAMS.TASK_CONTAINER_CONSUMER_NO
     *
     * @param TASK_CONTAINER_CONSUMER_NO the value for GTW_CHANNEL_ISO_INT_PARAMS.TASK_CONTAINER_CONSUMER_NO
     */
    public void setTASK_CONTAINER_CONSUMER_NO(BigDecimal TASK_CONTAINER_CONSUMER_NO) {
        this.TASK_CONTAINER_CONSUMER_NO = TASK_CONTAINER_CONSUMER_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_CHANNEL_ISO_INT_PARAMS.TASK_CONTAINER_SESSION_NO
     *
     * @return the value of GTW_CHANNEL_ISO_INT_PARAMS.TASK_CONTAINER_SESSION_NO
     */
    public BigDecimal getTASK_CONTAINER_SESSION_NO() {
        return TASK_CONTAINER_SESSION_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_CHANNEL_ISO_INT_PARAMS.TASK_CONTAINER_SESSION_NO
     *
     * @param TASK_CONTAINER_SESSION_NO the value for GTW_CHANNEL_ISO_INT_PARAMS.TASK_CONTAINER_SESSION_NO
     */
    public void setTASK_CONTAINER_SESSION_NO(BigDecimal TASK_CONTAINER_SESSION_NO) {
        this.TASK_CONTAINER_SESSION_NO = TASK_CONTAINER_SESSION_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_CHANNEL_ISO_INT_PARAMS.TASK_CONTAINER_DESTINATION
     *
     * @return the value of GTW_CHANNEL_ISO_INT_PARAMS.TASK_CONTAINER_DESTINATION
     */
    public String getTASK_CONTAINER_DESTINATION() {
        return TASK_CONTAINER_DESTINATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_CHANNEL_ISO_INT_PARAMS.TASK_CONTAINER_DESTINATION
     *
     * @param TASK_CONTAINER_DESTINATION the value for GTW_CHANNEL_ISO_INT_PARAMS.TASK_CONTAINER_DESTINATION
     */
    public void setTASK_CONTAINER_DESTINATION(String TASK_CONTAINER_DESTINATION) {
        this.TASK_CONTAINER_DESTINATION = TASK_CONTAINER_DESTINATION == null ? null : TASK_CONTAINER_DESTINATION.trim();
    }
}