package com.path.gateway.dbmaps.vo;

import com.path.lib.vo.BaseVO;
import java.math.BigDecimal;

public class GTW_CHANNEL_JMSVOKey extends BaseVO {
    /**
     * This field corresponds to the database column GTW_CHANNEL_JMS.CHANNEL_JMS_ID
     */
    private BigDecimal CHANNEL_JMS_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GTW_CHANNEL_JMS.CHANNEL_JMS_ID
     *
     * @return the value of GTW_CHANNEL_JMS.CHANNEL_JMS_ID
     */
    public BigDecimal getCHANNEL_JMS_ID() {
        return CHANNEL_JMS_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GTW_CHANNEL_JMS.CHANNEL_JMS_ID
     *
     * @param CHANNEL_JMS_ID the value for GTW_CHANNEL_JMS.CHANNEL_JMS_ID
     */
    public void setCHANNEL_JMS_ID(BigDecimal CHANNEL_JMS_ID) {
        this.CHANNEL_JMS_ID = CHANNEL_JMS_ID;
    }
}